---
deployment:
  tasks:
    - export DEPLOYPATH=/home/akkefkao/public_html
    - export HOME=/home/akkefkao
    # Navigate to the repository directory
    - source /home/akkefkao/.nvm/nvm.sh
    - cd $HOME/repositories/akkecs_group
    # Install dependencies
    - npm install --production
    # Build the application
    - npm run build
    # Copy the built files
    - /bin/cp -R out/* $DEPLOYPATH/
    - /bin/cp -R public/* $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/ 